axel <- function(){
  par <- c(-0.041, 0.1331, 0.306, 0.3586, 0.4153)
  names(par) <- c("a", "b", "rho", "m", "sigma")
  x <- seq(-1.5, 1.5, 0.02)
  w <- svi(x, par)
  du <- durrleman(x, par)
  plot(x, du, main="Axel-Vogt: Durrleman", type="l")
  abline(v=0, h=0, lty=3)
  plot(x,w, main="Axel-Vogt: Surface", ylim=c(0,0.18))
  abline(v=0, h=0, lty=3)
  assign("par", par, .GlobalEnv)
  w <- svi(x, par)
  assign("x", x, .GlobalEnv)
  assign("w", w, .GlobalEnv)
}
